### ISSUE TITLE
Membership List page tab title should be Membership - MSC

### ISSUE THREAD

**Issue by idevtech** [bradnoble/msc-vuejs#70] opened 2018-06-01 21:05 UTC
By convention and for SEO the format "section - app" is often used. For example, "Membership - MSC" for the membership page/section and MSC for the app title.

**Comment by bradnoble** [comment] 2018-06-01 22:39
duplicate of #33

**Comment by seekingsnowflakes** [comment] 2019-01-08 03:05
Closing as duplicate.

**Closed by seekingsnowflakes** 2019-01-08 03:05 UTC
Labels: Component: General, Priority: Medium, Status: Duplicate, Type: Change
