### ISSUE TITLE
Default sort for 'list' should be first name

### ISSUE THREAD

**Issue by bradnoble** [bradnoble/msc-vuejs#21] opened 2018-03-05 22:41 UTC
This may complicate the views in Cloudant -- testing on 3/5 suggested that reordering the keys in the 'householdsAndPeople' view broke the 'admin' view. Needs further investigation.

**Comment by idevtech** [comment] 2018-05-18 11:47
Duplicate of #17

**Comment by seekingsnowflakes** [comment] 2018-11-28 04:16
Conflicts with #29 and #17. Review for closure - believe group decision has decided on last,first.

**Comment by seekingsnowflakes** [comment] 2019-01-08 03:07
Closing as duplicate.

**Closed by seekingsnowflakes** 2019-01-08 03:07 UTC
Labels: Component: Members, Priority: High, Status: Duplicate, Type: Change
